<div class="cssDashboardPlugin grid_16">
    <div class="cssToolBox">
        <div class="cssToolboxHead">
            <img src="img/icon_plugin_25.png" title="Module">
            <span class="cssDashboardBoxHead">
                <?= $this->translate('Example Module') ?>
            </span>
        </div>
        <div>
            this is the dashboard index view.
            foo > bar
        </div>
    </div>
</div>